//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremierLeague_MatchFixtures
    {
        public int MatchId { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public Nullable<int> HomeTeamGoals { get; set; }
        public Nullable<int> AwayTeamGoals { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public string Status { get; set; }
        public string TeamWon { get; set; }
        public Nullable<System.DateTime> Metric_DateTimeCreated { get; set; }
        public byte[] HomeTeamImage { get; set; }
        public byte[] AwayTeamImage { get; set; }
    }
}
