//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremierLeague_Teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PremierLeague_Teams()
        {
            this.PremierLeague_History = new HashSet<PremierLeague_History>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamShortName { get; set; }
        public Nullable<System.DateTime> Metric_DateTimeCreated { get; set; }
        public string Disable { get; set; }
        public string Group { get; set; }
        public byte[] TeamImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PremierLeague_History> PremierLeague_History { get; set; }
    }
}
