//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremierLeague_History
    {
        public int HistoryId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamShortName { get; set; }
        public Nullable<int> Played { get; set; }
        public Nullable<int> Won { get; set; }
        public Nullable<int> Drawn { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> GoalsForward { get; set; }
        public Nullable<int> GoalsAgainst { get; set; }
        public byte[] TeamImage { get; set; }
    
        public virtual PremierLeague_Teams PremierLeague_Teams { get; set; }
    }
}
