//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishFootballLeague.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Football_PremierLeagueEntities : DbContext
    {
        public Football_PremierLeagueEntities()
            : base("name=Football_PremierLeagueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PremierLeague_History> PremierLeague_History { get; set; }
        public virtual DbSet<PremierLeague_MatchFixtures> PremierLeague_MatchFixtures { get; set; }
        public virtual DbSet<PremierLeague_Standings> PremierLeague_Standings { get; set; }
        public virtual DbSet<PremierLeague_Teams> PremierLeague_Teams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
